### ISSUE TITLE
[BUG] module.json malformed for v12.x

### ISSUE THREAD

**Issue by LeCuay** [jacobwojoski/dice-stats#165]
# Summary

Seems like one of the properties is incorrectly set on the `module.json`.

![Image](https://github.com/user-attachments/assets/ccf81a10-93a4-45ef-93ea-8ebf961f78af)

**Comment by jacobwojoski** [comment]
I'll look into this. 

I had some issues with getting versions working that I thought I fixed. Might require Uninstalling and reinstalling the latest v12 version though. Will check later

**Comment by jacobwojoski** [comment]
Okay, I was able to install it on Version 12 Build 343 from scratch. I'd suggest trying to uninstall and reinstall if you are on V12.

![Image](https://github.com/user-attachments/assets/14a8b507-c01b-4f9f-a01d-85adee922ff5)

**Comment by jacobwojoski** [comment]
Ah, I think I updated the top lvl module.json doc but not the one in the zip. 

Prob need to remake the zip. And yeah. Def messed up the releases and will update all the latest to point to last v12 patch. 

Thanks for the info.

**Comment by jacobwojoski** [comment]
Okay problem should be fixed but need to uninstall and download again. Should pull 1.21.4 If your still on Foundry V12

**Comment by malde** [comment]
When updating the already installed old version in v12 it's still throwing the error, but there is probably nothing you can do about it at this point. A fresh install updates as expected, so I'd consider this closed 👍

**Comment by jacobwojoski** [comment]
Yeah not much I can do about that. Now. Thanks for the help.
